# Generated by Django 4.2.30 on 2026-05-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_rss_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newsletter_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
