version: "3"
services:
  blog_app:
    image: ghcr.io/nikilyushkin/blog:${GITHUB_SHA:-latest}
    command: make docker-run-production
    container_name: blog_app
    environment:
      - TZ="Pacific/Auckland"
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - POSTGRES_DB=vas3k_blog
      - POSTGRES_USER=vas3k
      - POSTGRES_PASSWORD=vas3k
      - POSTGRES_HOST=postgres
      - TELEGRAM_TOKEN  # values below come from .env
      - TELEGRAM_MAIN_CHAT_ID
      - SENTRY_DSN
      - PATREON_CLIENT_ID
      - PATREON_CLIENT_SECRET
#      - CLUB_OPENID_CONFIG_SECRET
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8022:8022"

  postgres:
    image: postgres:15
    container_name: blog_postgres
    restart: always
    environment:
      - TZ="Pacific/Auckland"
      POSTGRES_USER: vas3k
      POSTGRES_PASSWORD: vas3k
      POSTGRES_DB: vas3k_blog
    volumes:
      - /home/ubuntu/pgdata_heynik_blog:/var/lib/postgresql/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:54324:5432"
